### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tomdyson** [Dani4kor/wagtail-heroku#1]
This is great, @Dani4kor! Do you have any plans to extend it? I think a simple, good looking, easy-to-install blog would be a great driver for Wagtail adoption.

**Comment by Dani4kor** [comment]
ty @tomdyson , yea! I share your concern about extend it, Wagtail presents itself - versatile, 
beautiful & user-friend CMS i think need to follow this "wagteil-way"

Main idea to build out-of box Wagtail/Django(template only) blog with nice views & backend power improvement/expansion  for example:
- fix boostrap or rewrite to clean css & design(wagtail design/colors, idk)
- **add/configure Wagtail CMS moduls/apps -> Streamfield, Simple img-board,  search, social services integration etc, logging**
- **Implement Wagtail CMS into light Django template -> for better community support & integration**
- **Security, easyway to production/debug mode, static compression**
- Configure out-of-box installation, docs, some examples & test
- ?????
- PROFIT
